### ISSUE TITLE
Register more then one font fails

### ISSUE THREAD

**Issue by piscis** [eVisit/react-native-dynamic-fonts#1]
Hi I'm trying to register multiple fonts in an iOS app but it fails. The text view is not using the new Font. How ever if i resiter only one font everything works as expected.

**Comment by th317erd** [comment]
Any chance you could upload the two fonts in question, and specify in which order you are loading them?

**Comment by piscis** [comment]
Hi @th317erd,

I can not share them because of license restrictions. 

However it looks like the problem is with the font it self. I tried to convert some fonts from Google Fonts and they work as expected.

I then used https://transfonter.org/ to convert my fonts from TTF to TTF and they got smaller and now they work. So my guess is that there must be something wrong original fonts I used.

Again sorry for the trouble and thank you for the excellent module!

**Comment by th317erd** [comment]
Ah, cool! Thanks for the feedback. Reopen the issue if you still run into problems.
