### ISSUE TITLE
Font load promise will reject during live reload

### ISSUE THREAD

**Issue by piscis** [eVisit/react-native-dynamic-fonts#3]
Hi,

I noticed that during the development if live reload is turned on the font load promise will reject loading fonts a second time. 

Example:

- Start the app.
- Font loads and console output reads: `Loaded font successfully. Font name is:  BubblerOne`
- Make a change and save.
- Live reload will reload the app.
- Promise will reject with following failure: `Failed to register font: %@`

While this is not a problem in general. It is a problem if you like to do someting like:

    async function foo(fonts) {
      for (let font of fonts) {
        await loadFont(font.name, font.content, font.type);
      }
 
      this.setState('fontsLoaded': true);
    }

If you do some sort of batch loading and want fonts register in a sequence  you have to handle the promise reject.

Like here: https://gist.github.com/piscis/c26497f680fca8ecbd2429d7edabd50b

**Comment by th317erd** [comment]
Thanks for reporting this issue @piscis. I will look into checking if the font is already loaded before attempting to load it again. I am not exactly sure when I will be able to look into this (really busy at the moment)

**Comment by virgil9306** [comment]
@piscis : Even if I do the method you mentioned in your file with Live Reloading off, I get the following promise rejection:
```
Possible Unhandled Promise Rejection (id: 0):
Error: Name is a required argument
Error: Name is a required argument
```

Any ideas...?

----

Code Sample:

```
class MyComponent extends Component {
  ...
  _handleFontLoad () {
    loadFonts(FONT_LIST).then(() => {
      this.setState({loaded: true});
    });
  }
```
```
async function loadFonts(fontsList) {
  return new Promise((resolve, reject) => {
    const task = (font, cb) => {
        loadFont(font.name, font.content, font.type).then(function(name) {
        console.log('Loaded font successfully. Font name is: ', name);
        cb();
      }).catch((e) => {
        console.log(e, font.name);
        cb();
      });
    };

    const finalizer = (err) => {
      resolve();
    };

    async.eachLimit(fontsList, 1, task, finalizer);
  });
}
```

**Comment by th317erd** [comment]
@virgil9306 @piscis I added `loadFonts` in `v0.2.1`. I also added checking if the font is already loaded, but I ONLY added it to the JS code... so this probably won't help (it might help for Hot Reloading, but probably not for Live reloading). I don't have time right now to add the checking to the native code. I would happily accept a PR though.

**Comment by virgil9306** [comment]
@th317erd Thank you! This solved my particular issue, but as you said it's not on the native code. Unfortunately I am not able to help with that (my machine is a PC), but thanks a lot for your responsiveness...

**Comment by th317erd** [comment]
No problem! I will leave this issue open until I am able to fully fix it with native code. :)

**Comment by th317erd** [comment]
@virgil9306 @piscis This issue has now been fully resolved by @99ff00 (thanks @99ff00!). I am closing this issue. Thanks for all the feedback and help guys!
