### ISSUE TITLE
(Android) Custom font only renders when the styles are also provided the correct `fontWeight`

### ISSUE THREAD

**Issue by chrismllr** [eVisit/react-native-dynamic-fonts#8]
Given the following styles:

```js
<TouchableOpacity>
  <Text
    style={{
      fontFamily: theme.fonts.primary,
      fontSize: 16,
      textAlign: 'center',
      fontWeight: '300' // different font weight
    }}
  >
    Im a button
  </Text>
</TouchableOpacity>

<TouchableOpacity>
  <Text
    style={{
      fontFamily: theme.fonts.primary,
      fontSize: 16,
      textAlign: 'center',
      fontWeight: '600' // correct font weight
    }}
  >
    Im a button
  </Text>
</TouchableOpacity>
```

Output is this
<img width="130" alt="screen shot 2017-11-10 at 10 26 01 am" src="https://user-images.githubusercontent.com/9942917/32667941-de00a584-c601-11e7-804a-0bd437f4b556.png">

But this does not occur on iOS.

Is there any logical reason for this that you've encountered?

If this is to be the case, is there a way to derive the correct font-weight after loading the font?

Thank you

**Comment by th317erd** [comment]
@chrismllr What type of font are you using (ttf or otf)? Also, have you paid attention to the return value from loadFont(s) to see what font name was ACTUALLY loaded?

**Comment by chrismllr** [comment]
It is a `ttf` font, and on android it is loading the name that I have defined for it, per docs

**Comment by th317erd** [comment]
So what is the issue exactly?

**Comment by chrismllr** [comment]
As I am dynamically loading a font, I may not know what font weight it has. Is it possible to also derive that, along with the font name, when resolving `loadFonts`? Otherwise, I will have to hard code a random value as `fontWeight` in every element that uses that font

**Comment by th317erd** [comment]
I am not sure exactly what is wrong. For now, no, none of the font information is loaded / known to the font loader. It simply decodes it and passes it off to RN. I hope in the future to add support for reading the font headers to provide more information, but unfortunately I don't have the time to add that at the moment.

Are you sure something else isn't happening? Those look like two very different fonts to me. If you need to set a default app wide, I recommend cascading styles, i.e. ```javascript
include fontStyle from './font-style';

...

... style={{ ...fontStyle, color: 'red' }}
```

Or create your own text component as the React team recommends: https://facebook.github.io/react-native/docs/text.html#limited-style-inheritance

**Comment by chrismllr** [comment]
Yep, the first font is the system font (i.e. the custom font is not rendering), the custom font only renders when the correct `fontWeight` is applied (which i only discovered by trying a bunch of different font weights until it worked)

**Comment by chrismllr** [comment]
This provides a limitation for me, as the dynamic font is out of my control (it is configuration based, loaded from an API call)

The option for me would be the user, while uploading the font to be loaded, typing the weight of the font uploaded so I can reference that after dynamically loading into the app. 

Do you think this is the direction to proceed?

**Comment by th317erd** [comment]
@chrismllr Have you tried just not specifying a weight?

You might spend some time reading about how font's work. Any decent font will have multiple weights specified as part of the font, but not all fonts have this, and only support one weight. You also need to load all weights for a font family, as this usually won't happen automatically. This is unavoidable, and isn't an issue with this module or with React Native. Really it boils down to an issue with performance and how fonts work, and that no one has yet come up with a good algorithm that has been widely adopted to dynamically "thicken" fonts.

What you probably need to do is load all weights for whatever font you are using. For example, if you are using "OpenSans", you probably need to load "OpenSans-Regular", "OpenSans-Bold", "OpenSans-SemiBold", "OpenSans-Italic", "OpenSans-ItalicBold", etc... At this point the `fontWeight` will work as you expect it to.

Some potentially good reads:
http://fontfeed.com/archives/styles-weights-widths-it%E2%80%99s-all-in-the-type-family/

https://medium.com/@tiro/https-medium-com-tiro-introducing-opentype-variable-fonts-12ba6cd2369

http://jcgt.org/published/0006/02/02/paper.pdf

**Comment by th317erd** [comment]
Also @chrismllr React Native (and React on web) will work if you specify weights as "normal" and "bold". I am not sure if this will work any better for you, but I imagine (without testing it) that it will continue to render the font even if it isn't the thickness you expect. https://facebook.github.io/react-native/docs/textstyleproptypes.html#fontweight

**Comment by chrismllr** [comment]
Yeah, this all makes total sense. I should be loading all of the weights of the font in our project in order to get the right consistency. Thanks for the resources! I will also try `normal` vs `bold` and see how that behaves. I'm happy closing the ticket via the resources you provided 👍

**Comment by th317erd** [comment]
Thanks @chrismllr. Let me know if you have any further questions! :)
